In [122]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler,LabelEncoder 
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score,classification_report , confusion_matrix 
import joblib

In [123]:
from sklearn.datasets import load_iris

In [124]:
data =load_iris()

In [125]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [126]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [127]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [128]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [129]:
df['target']=data.target

In [130]:
df['target_names'] = df['target'].map({i:name for i ,name in enumerate(data.target_names)})

In [131]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [133]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [134]:
df['target_names'].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [135]:
binary_df = df[df['target']!=2]

In [136]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [137]:
binary_df['target_names'].unique()

array([np.str_('setosa'), np.str_('versicolor')], dtype=object)

In [138]:
binary_df['target'].unique()

array([0, 1])

In [139]:
x_binary=binary_df.drop(columns=['target','target_names'])
y_binary=binary_df['target']

In [140]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [141]:
y_binary

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [142]:
x_train,x_test,y_train,y_test =  train_test_split(x_binary,y_binary,test_size=0.2 ,random_state=42)
                                                

In [143]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           80.00000         80.000000          80.000000   
mean             5.47250          3.075000           2.897500   
std              0.65429          0.470524           1.420107   
min              4.30000          2.000000           1.100000   
25%              5.00000          2.800000           1.500000   
50%              5.40000          3.000000           3.300000   
75%              5.92500          3.400000           4.300000   
max              7.00000          4.400000           4.900000   

       petal width (cm)  
count         80.000000  
mean           0.805000  
std            0.555046  
min            0.100000  
25%            0.200000  
50%            1.000000  
75%            1.300000  
max            1.600000

In [144]:
x_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
83                6.0               2.7                5.1               1.6
53                5.5               2.3                4.0               1.3
70                5.9               3.2                4.8               1.8
45                4.8               3.0                1.4               0.3
44                5.1               3.8                1.9               0.4
39                5.1               3.4                1.5               0.2
22                4.6               3.6                1.0               0.2
80                5.5               2.4                3.8               1.1
10                5.4               3.7                1.5               0.2
0                 5.1               3.5                1.4               0.2
18                5.7               3.8                1.7               0.3
30                4.8               3.1                1.6               0.2
73                6.1               2.8                4.7               1.2
33                5.5               4.2                1.4               0.2
90                5.5               2.6                4.4               1.2
4                 5.0               3.6                1.4               0.2
76                6.8               2.8                4.8               1.4
77                6.7               3.0                5.0               1.7
12                4.8               3.0                1.4               0.1
31                5.4               3.4                1.5               0.4

In [145]:
print(y_binary.value_counts()) 

target
0    50
1    50
Name: count, dtype: int64


In [146]:
scaler = StandardScaler()
x_train_scaled =scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [147]:
svm_binary = SVC(kernel='linear',C=1.0,probability=True)

In [148]:
svm_binary.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [149]:
svm_binary.predict(x_test_scaled)

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [150]:
print(classification_report(y_test,svm_binary.predict(x_test_scaled)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [151]:
confusion_matrix(y_test,svm_binary.predict(x_test_scaled))

array([[12,  0],
       [ 0,  8]])

In [152]:
joblib.dump(svm_binary,'svm_binary.pkl')

['svm_binary.pkl']

In [154]:
# Save the scaler
joblib.dump(scaler, 'svm_binary_scaler.pkl')


['svm_binary_scaler.pkl']

### Multiclass Classifcaiton

In [47]:
x_multi = df[['sepal length (cm)',	'sepal width (cm)',	'petal length (cm)',	'petal width (cm)'	]]

In [48]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [49]:
y_multi = df['target']

In [50]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [51]:
x_train_multi , x_test_multi , y_train_multi , y_test_multi = train_test_split(x_multi,y_multi,test_size=.2)

In [52]:
svm_multi = SVC(kernel="linear")

In [53]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(kernel='linear')

In [54]:
svm_multi.predict(x_test_multi)

array([0, 2, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 0, 2, 1])

In [55]:
print("report for multi class svc \n",classification_report(y_test_multi ,svm_multi.predict(x_test_multi) ))

report for multi class svc 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.93      0.96        14
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30



In [56]:
confusion_matrix(y_test_multi ,svm_multi.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  8]])

In [57]:
joblib.dump(svm_multi,"svm_multi.pkl")

['svm_multi.pkl']

### Logistic Regression

#### Binary class classification

In [33]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
29                4.7               3.2                1.6               0.2
2                 4.7               3.2                1.3               0.2
72                6.3               2.5                4.9               1.5
85                6.0               3.4                4.5               1.6
11                4.8               3.4                1.6               0.2
..                ...               ...                ...               ...
45                4.8               3.0                1.4               0.3
81                5.5               2.4                3.7               1.0
41                4.5               2.3                1.3               0.3
61                5.9               3.0                4.2               1.5
77                6.7               3.0                5.0               1.7

[80 rows x 4 columns]

In [34]:
x_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
38                4.4               3.0                1.3               0.2
88                5.6               3.0                4.1               1.3
94                5.6               2.7                4.2               1.3
14                5.8               4.0                1.2               0.2
76                6.8               2.8                4.8               1.4
79                5.7               2.6                3.5               1.0
80                5.5               2.4                3.8               1.1
71                6.1               2.8                4.0               1.3
75                6.6               3.0                4.4               1.4
99                5.7               2.8                4.1               1.3
49                5.0               3.3                1.4               0.2
23                5.1               3.3                1.7               0.5
42                4.4               3.2                1.3               0.2
30                4.8               3.1                1.6               0.2
35                5.0               3.2                1.2               0.2
92                5.8               2.6                4.0               1.2
24                4.8               3.4                1.9               0.2
9                 4.9               3.1                1.5               0.1
51                6.4               3.2                4.5               1.5
22                4.6               3.6                1.0               0.2

In [35]:
y_train

29    0
2     0
72    1
85    1
11    0
     ..
45    0
81    1
41    0
61    1
77    1
Name: target, Length: 80, dtype: int64

In [36]:
y_test

38    0
88    1
94    1
14    0
76    1
79    1
80    1
71    1
75    1
99    1
49    0
23    0
42    0
30    0
35    0
92    1
24    0
9     0
51    1
22    0
Name: target, dtype: int64

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
x_train_scaled

array([[-1.25016253,  0.18012613, -0.88313048, -1.05022261],
       [-1.25016253,  0.18012613, -1.08971071, -1.05022261],
       [ 1.31017033, -1.2208549 ,  1.38925205,  1.24438141],
       [ 0.83010792,  0.58040643,  1.11381174,  1.42088941],
       [-1.09014173,  0.58040643, -0.88313048, -1.05022261],
       [ 0.83010792, -1.82127534,  0.76951136,  0.3618414 ],
       [-0.93012092, -0.02001401, -0.95199056, -1.05022261],
       [ 0.35004551, -0.62043446,  1.11381174,  0.8913654 ],
       [ 0.1900247 , -1.2208549 ,  0.70065128,  0.5383494 ],
       [-0.77010012,  0.58040643, -0.95199056, -1.05022261],
       [ 0.0300039 , -1.62113519,  0.76951136,  0.8913654 ],
       [-0.93012092, -0.22015416, -1.02085064, -1.05022261],
       [ 1.95025355, -0.02001401,  1.25153189,  1.24438141],
       [ 0.35004551, -0.42029431,  0.90723151,  0.8913654 ],
       [-0.61007932,  1.18082687, -0.95199056, -0.6972066 ],
       [-0.1300169 ,  1.58110716, -0.81427041, -0.6972066 ],
       [ 0.51006631, -0.

In [39]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train_scaled,y_train)

LogisticRegression()

In [42]:
y_pred = logistics_binary.predict(x_test_scaled)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [45]:
confusion_matrix(y_test,y_pred)

array([[10,  0],
       [ 0, 10]])

In [46]:
joblib.dump(logistics_binary,'logistics_binary.pkl')

['logistics_binary.pkl']

#### Multiclass Classification

In [58]:
#this is multi class data
x_train_multi 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
143                6.8               3.2                5.9               2.3
39                 5.1               3.4                1.5               0.2
105                7.6               3.0                6.6               2.1
27                 5.2               3.5                1.5               0.2
95                 5.7               3.0                4.2               1.2
..                 ...               ...                ...               ...
126                6.2               2.8                4.8               1.8
26                 5.0               3.4                1.6               0.4
4                  5.0               3.6                1.4               0.2
40                 5.0               3.5                1.3               0.3
19                 5.1               3.8                1.5               0.3

[120 rows x 4 columns]

In [59]:
x_test_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
41                 4.5               2.3                1.3               0.3
102                7.1               3.0                5.9               2.1
14                 5.8               4.0                1.2               0.2
57                 4.9               2.4                3.3               1.0
37                 4.9               3.6                1.4               0.1
49                 5.0               3.3                1.4               0.2
28                 5.2               3.4                1.4               0.2
67                 5.8               2.7                4.1               1.0
91                 6.1               3.0                4.6               1.4
56                 6.3               3.3                4.7               1.6
32                 5.2               4.1                1.5               0.1
90                 5.5               2.6                4.4               1.2
88                 5.6               3.0                4.1               1.3
34                 4.9               3.1                1.5               0.2
136                6.3               3.4                5.6               2.4
75                 6.6               3.0                4.4               1.4
66                 5.6               3.0                4.5               1.5
81                 5.5               2.4                3.7               1.0
69                 5.6               2.5                3.9               1.1
118                7.7               2.6                6.9               2.3
82                 5.8               2.7                3.9               1.2
124                6.7               3.3                5.7               2.1
142                5.8               2.7                5.1               1.9
83                 6.0               2.7                5.1               1.6
125                7.2               3.2                6.0               1.8
65                 6.7               3.1                4.4               1.4
110                6.5               3.2                5.1               2.0
10                 5.4               3.7                1.5               0.2
149                5.9               3.0                5.1               1.8
62                 6.0               2.2                4.0               1.0

In [61]:
y_train_multi

143    2
39     0
105    2
27     0
95     1
      ..
126    2
26     0
4      0
40     0
19     0
Name: target, Length: 120, dtype: int64

In [62]:
y_test_multi

41     0
102    2
14     0
57     1
37     0
49     0
28     0
67     1
91     1
56     1
32     0
90     1
88     1
34     0
136    2
75     1
66     1
81     1
69     1
118    2
82     1
124    2
142    2
83     1
125    2
65     1
110    2
10     0
149    2
62     1
Name: target, dtype: int64

In [63]:
logistics_ovr = LogisticRegression(multi_class='ovr',solver='lbfgs',max_iter=2000)

In [64]:
logistics_ovr.fit(x_train_multi,y_train_multi)

c:\Users\kumar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [65]:
logistics_ovr.predict(x_test_multi)

array([0, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 0, 2, 1])

In [66]:
print("classificatoin repost for ovr logistics \n" , classification_report(y_test_multi , logistics_ovr.predict(x_test_multi)))

classificatoin repost for ovr logistics 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.86      0.92        14
           2       0.80      1.00      0.89         8

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30



In [67]:
confusion_matrix(y_test_multi , logistics_ovr.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0, 12,  2],
       [ 0,  0,  8]])

In [74]:
joblib.dump(logistics_ovr,'logistic_ovr.pkl')

['logistic_ovr.pkl']

In [68]:
logistics_multinomial  = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=2000)

In [69]:
logistics_multinomial.fit(x_train_multi,y_train_multi)

c:\Users\kumar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='multinomial')

In [70]:
logistics_multinomial.predict(x_test_multi)

array([0, 2, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 0, 2, 1])

In [71]:
confusion_matrix(y_test_multi,logistics_multinomial.predict(x_test_multi) )

array([[ 8,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  8]])

In [72]:
print("the classificatoin report for multinomila multi class logistics is \n" , classification_report(y_test_multi,logistics_multinomial.predict(x_test_multi) ))

the classificatoin report for multinomila multi class logistics is 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.93      0.96        14
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30



In [76]:
joblib.dump(logistics_multinomial,'logistics_multinomial.pkl')

['logistics_multinomial.pkl']